TaxiServiceWebUI/Areas/Admin/Controllers/PriceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Abstract;
using Entities.Concrete;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TaxiServiceWebUI.Areas.Admin.Models;

namespace TaxiServiceWebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PriceController : Controller
    {
        private IPriceService _priceService;
        private IAddressService _addressService;
        public PriceController(IPriceService priceService, IAddressService addressService)
        {
            _priceService = priceService;
            _addressService = addressService;
        }
        public IActionResult Index()
        {
            var priceList = _priceService.GetAllPrices();
            PriceListViewModel model = new PriceListViewModel
            {
                Prices = priceList
            };

            return View(model);
        }

        public IActionResult Add()
        {
            ViewBag.Addresses = new SelectList(_addressService.GetAddressList(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Add(Price price)
        {
            try
            {
                Price oppositePrice = new Price();
                oppositePrice.StartAddress = price.EndAddress;
                oppositePrice.EndAddress = price.StartAddress;
                oppositePrice.TravelTime = price.TravelTime;
                oppositePrice.OneWayPrice = price.OneWayPrice;
                oppositePrice.TwoWayPrice = price.TwoWayPrice;
                oppositePrice.Distance = price.Distance;
                _priceService.Add(oppositePrice);
                _priceService.Add(price);
            }
            catch (Exception e)
            {

                ViewBag.Error = e.InnerException;
            }
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int priceId)
        {
            _priceService.Delete(priceId);
            return RedirectToAction("Index");
        }

    }
}

TaxiServiceWebUI/Controllers/ResortController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using TaxiServiceWebUI.Models;

namespace TaxiServiceWebUI.Controllers
{
    public class ResortController : Controller
    {
        private IResortService _resortService;

        public ResortController(IResortService resortService)
        {
            _resortService = resortService;
        }
        public IActionResult List()
        {
            var resorts = _resortService.GetResorts();
            ResortListViewModel model = new ResortListViewModel()
            {
                Resorts = new List<Entities.Concrete.Resort>()
            };
            return View(model);
        }
    }
}

TaxiServiceWebUI/Areas/Admin/Views/Shared/_Layout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Innsbruck Taxi | Admin</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link href="~/css/fontawesome/all.min.css" rel="stylesheet" />
    <link href="~/css/icofont/icofont.min.css" rel="stylesheet" />
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link href="~/css/tempusdominus/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />
    <!-- iCheck -->
    <link href="~/css/icheck-bootstrap/icheck-bootstrap.min.css" rel="stylesheet" />
    <!-- JQVMap -->
    <link href="~/css/jqvmap/jqvmap.min.css" rel="stylesheet" />
    <!-- Theme style -->
    <link href="~/css/adminlte/adminlte.min.css" rel="stylesheet" />
    <!-- overlayScrollbars -->
    <link href="~/css/overlayscrollbars/OverlayScrollbars.min.css" rel="stylesheet" />
    <!-- Daterange picker -->
    <link href="~/css/daterangepicker/daterangepicker.css" rel="stylesheet" />
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <script src="~/js/adminlte/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/js/jquery/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="~/js/bootstrap/bootstrap.bundle.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/js/overlayscrollbars/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/js/adminlte/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/js/adminlte/demo.js"></script>
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-dark navbar-lightblue">

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Notifications Dropdown Menu -->
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="icofont-settings icofont-2x"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <a href="#" class="dropdown-item">
                            <i class="icofont-logout"></i>Çıkış Yap
                        </a>
                        <div class="dropdown-divider"></div>
                    </div>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="" class="brand-link">
                <img src="~/images/taxi_logo.png" alt="Innsbruck Taxi" class="brand-image img-circle elevation-3"
                     style="opacity: .8" />
                <span class="brand-text font-weight-light">Inssbruck</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/images/logo.png" class="img-circle elevation-2" />
                    </div>
                    <div class="info">
                        <div style="color:white; padding-left: 10px;" class="d-block">Innsbruck Taxi</div>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-item has-treeview">
                            <a href="@Url.Action("Index","Price", new { area = "Admin" })" class="nav-link">
                                <i class="icofont-page"></i>
                                <p>
                                    Adres - Fiyat Yönetimi
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="@Url.Action("List","Address", new { area = "Admin" })" class="nav-link">
                                <i class="icofont-bars accent-green"></i>
                                <p>
                                    Adres Yönetimi
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="@Url.Action("Index","Resort", new { area = "Admin" })" class="nav-link">
                                <i class="icofont-bars accent-green"></i>
                                <p>
                                    Resort Yönetimi
                                </p>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">Yönetim Paneli</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Yönetim Paneli</a></li>
                                <li class="breadcrumb-item active">Ana Sayfa</li>
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            <section class="content">
                @RenderBody()
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong>Copyright &copy; 2020 <a href="#">Innsbruck Taxi</a>.</strong>
            Tüm hakları saklıdır.
            <div class="float-right d-none d-sm-inline-block">
                <b>Versiyon</b> 1.0.2
            </div>
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
   
</body>
</html>