TaxiServiceWebUI/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TaxiServiceWebUI.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult List()
        {
            return View();
        }
    }
}

TaxiServiceWebUI/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TaxiServiceWebUI.Models;

namespace TaxiServiceWebUI.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Info()
        {
            return View();
        }
        [HttpPost]
        public IActionResult SendMail(ContactSendMailViewModel model)
        {
            if (ModelState.IsValid)
            {
                SendContactMail(model);
                return RedirectToAction(nameof(Info));
            }
            return View("Info");
            
        }

        private void SendContactMail(ContactSendMailViewModel model)
        {
            var credentials = new NetworkCredential("infoinnsbrucktaxi@gmail.com", "info123456+");
            var mail = new MailMessage()
            {
                From = new MailAddress("infoinnsbrucktaxi@gmail.com"),
                Subject = model.ContactDTO.Subject,
                Body = "Hello " + model.ContactDTO.Name + "<br> We will return your message very soon, keep in touch.<br><br>" +
                "<h3 style:'color:green;'>Innsbruck Taxi<p>Call Us. 004366499398308 </p></h3>"
            };
            mail.IsBodyHtml = true;
            mail.To.Add(new MailAddress("infoinnsbrucktaxi@gmail.com"));
            mail.To.Add(new MailAddress(model.ContactDTO.Email));

            var client = new SmtpClient()
            {
                Port = 587,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Host = "smtp.gmail.com",
                EnableSsl = true,
                Credentials = credentials
            };
            client.Send(mail);
        }
    }
}

TaxiServiceWebUI/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using Business.Abstract;
using Entities.Concrete;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TaxiServiceWebUI.Dtos;
using TaxiServiceWebUI.Models;

namespace TaxiServiceWebUI.Controllers
{
    public class ReservationController : Controller
    {
        private readonly IBookingInfoService _infoService;
        private readonly IAddressService _addressService;
        private readonly IPriceService _priceService;
        private readonly IReservationService _reservationService;
        private readonly IResortService _resortService;
        public ReservationController(IBookingInfoService infoService, IAddressService addressService,
            IPriceService priceService, IReservationService reservationService, IResortService resortService)
        {
            _infoService = infoService;
            _addressService = addressService;
            _priceService = priceService;
            _reservationService = reservationService;
            _resortService = resortService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(ReservationHomeCalculateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var resorts = _resortService.GetResorts();
                ReservationHomeCalculateViewModel returnModel = new ReservationHomeCalculateViewModel()
                {
                    Resorts = resorts,
                    Booking = null

                };
                ViewBag.Addresses = new SelectList(_addressService.GetAddressList(), "Id", "Name");
                return View("../Home/Index", returnModel);
            }
            BookingInfo bookingInfo = new BookingInfo();
            var priceInfo = _priceService.GetBookingPrice((int)model.Booking.FromId, (int)model.Booking.ToId);
            var fromAddress = _addressService.GetAddressById((int)model.Booking.FromId);
            var toAddress = _addressService.GetAddressById((int)model.Booking.ToId);
            if (model.Booking.TransferType == 1)
            {
                bookingInfo.Price = priceInfo.OneWayPrice;
            }
            else
            {
                bookingInfo.Price = priceInfo.TwoWayPrice;
            }
            bookingInfo.Distance = priceInfo.Distance;
            bookingInfo.TravelTime = priceInfo.TravelTime;
            bookingInfo.FromId = (int)model.Booking.FromId;
            bookingInfo.ToId = (int)model.Booking.ToId;
            bookingInfo.Passenger = (int)model.Booking.Passenger;
            bookingInfo.VehicleType = (int)model.Booking.VehicleType;
            bookingInfo.TransferType = model.Booking.TransferType;
            bookingInfo.FromAddress = fromAddress.Data.Name;
            bookingInfo.ToAddress = toAddress.Data.Name;
            _infoService.Add(bookingInfo);
            return RedirectToAction("BookingService");
        }

        public IActionResult BookingService()
        {
            ViewBag.Addresses = new SelectList(_addressService.GetAddressList(), "Id", "Name");
            var info = _infoService.GetLastBookingInfo();
            if(!(info == null))
            {
                BookingInfoViewModel model = new BookingInfoViewModel
                {
                    BookingInfo = info
                };
                _infoService.Delete(info.Id);

                return View(model);
            }
            return View();
        }

        [HttpPost]
        public IActionResult Save(BookingInfoViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Addresses = new SelectList(_addressService.GetAddressList(), "Id", "Name");
                return View("BookingService");
            }
            Reservation reservation = new Reservation();
            var fromAddress = _addressService.GetAddressById(model.BookingInfo.FromId);
            var toAddress = _addressService.GetAddressById(model.BookingInfo.ToId);
            reservation.TransferDate = model.Reservation.TransferDate.Date;
            reservation.Address = model.Reservation.Address;
            reservation.ArrivalMinute = model.Reservation.ArrivalMinute;
            reservation.ArrivalTime = model.Reservation.ArrivalTime;
            reservation.Bag = model.Reservation.Bag;
            reservation.Ski = model.Reservation.Ski;
            reservation.Hotel = model.Reservation.Hotel;
            reservation.SnowBoard = model.Reservation.SnowBoard;
            reservation.FirstName = model.Reservation.FirstName;
            reservation.LastName = model.Reservation.LastName;
            reservation.Email = model.Reservation.Email;
            reservation.ExtraInformation = model.Reservation.ExtraInformation;
            reservation.PickUpAddress = fromAddress.Data.Name;
            reservation.DropOffAddress = toAddress.Data.Name;
            reservation.PhoneNumber = model.Reservation.PhoneNumber;
            reservation.PaymentOption = model.Reservation.PaymentOption;
            reservation.ReturnTransferDate = model.Reservation.ReturnTransferDate;
            reservation.ReturnPickUpTime = model.Reservation.ReturnPickUpTime;
            reservation.ReturnPickUpMinute = model.Reservation.ReturnPickUpMinute;

            _reservationService.Add(reservation);


            SendInformationMail(reservation.Email, reservation);

        
            var info = _reservationService.GetLastReservation();
            if (!(info == null))
            {
                var priceInfo = _priceService.GetBookingPrice(model.BookingInfo.FromId, model.BookingInfo.ToId);
                ViewBag.TransferType = model.BookingInfo.TransferType == 0 ? "One Way" : "Return";
                ViewBag.Price = model.BookingInfo.TransferType == 0 ? priceInfo.OneWayPrice : priceInfo.TwoWayPrice;
                ViewBag.Distance = priceInfo.Distance;
                ViewBag.TravelTime = priceInfo.TravelTime;
                ViewBag.Vehicle = "Taxi Max. 3 Pax";

                ReservationAddViewModel viewModel = new ReservationAddViewModel
                {
                    Reservation = info
                };
                return View(viewModel);
            }
            return RedirectToAction("BookingService");
        }

        private void SendInformationMail(string email, Reservation reservation)
        {
            string template = GetMailTemplate(reservation);
            var credentials = new NetworkCredential("infoinnsbrucktaxi@gmail.com", "info123456+");
            var mail = new MailMessage()
            {
                From = new MailAddress("infoinnsbrucktaxi@gmail.com"),
                Subject = "Reservation Summary",
                Body = template
                };
            mail.IsBodyHtml = true;
            mail.To.Add(new MailAddress("infoinnsbrucktaxi@gmail.com"));
            mail.To.Add(new MailAddress(email));

            var client = new SmtpClient()
            {
                Port = 587,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Host = "smtp.gmail.com",
                EnableSsl = true,
                Credentials = credentials
            };
            client.Send(mail);
        }

        private string GetMailTemplate(Reservation reservation)
        {
            string returnTimeInfo = reservation.ReturnTransferDate != null ? "<tr>" +
                "<td>Return Transfer Date</td>" +
                "<td>" + reservation.ReturnTransferDate + "</td>" +
                "</tr>" +
                 "<tr>" +
                "<td>Return Transfer Time</td>" +
                "<td>" + reservation.ReturnPickUpTime + ": "+reservation.ReturnPickUpMinute + "</td>" +
                "</tr>" +
                 "<tr>" : "";
           
            string htmlTemplate = "<!DOCTYPE html><html><head><style>table{font-family:arial,sans-serif;border-collapse:collapse;width:100%;}td, th {border: 1px solid #dddddd;  text-align: left;padding: 8px;}tr:nth-child(even) {background-color: #dddddd;}</style></head><body><h2>Reservation Summary</h2><h3>Hello "+ reservation.FirstName+"<br>We are so greatful for choosing us. Thanks a lot.<br>Your reservation information listed at below on the table which name is Reservation Summary.</h3><table><tr><th>Summary</th><th>Info</th></tr>" +
                "<tr>" +
                "<td>Pick Up Address</td>" +
                "<td>"+ reservation.PickUpAddress+"</td>" +
                "</tr>" +
                "<tr>" +
                "<td>Drop Off Address</td>" +
                "<td>" + reservation.DropOffAddress + "</td>" +
                "</tr>" +
                 "<tr>" +
                "<td>Transfer Date</td>" +
                "<td>" + reservation.TransferDate.Date.ToShortDateString() + "</td>" +
                "</tr>" + returnTimeInfo+
                "<td>Transfer Time</td>" +
                "<td>" + reservation.ArrivalTime + ":" + reservation.ArrivalMinute + "</td>" +
                "</tr>" +
                 "<tr>" +
                "<td>Address</td>" +
                "<td>" + reservation.Address+ "</td>" +
                "</tr>" +
                 "<tr>" +
                "<td>Hotel / Pension</td>" +
                "<td>" + reservation.Hotel+ "</td>" +
                "</tr>" +
                 "<tr>" +
                "<td>Name</td>" +
                "<td>" + reservation.FirstName +" " + reservation.LastName + "</td>" +
                "</tr>" +
                 "<tr>" +
                "<td>Bag</td>" +
                "<td>" + reservation.Bag+ "</td>" +
                "</tr>" +
                 "<tr>" +
                "<td>Ski</td>" +
                "<td>" + reservation.Ski+ "</td>" +
                "</tr>" +

TaxiServiceWebUI/Controllers/ResortController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using TaxiServiceWebUI.Models;

namespace TaxiServiceWebUI.Controllers
{
    public class ResortController : Controller
    {
        private IResortService _resortService;

        public ResortController(IResortService resortService)
        {
            _resortService = resortService;
        }
        public IActionResult List()
        {
            var resorts = _resortService.GetResorts();
            ResortListViewModel model = new ResortListViewModel()
            {
                Resorts = new List<Entities.Concrete.Resort>()
            };
            return View(model);
        }
    }
}

TaxiServiceWebUI/Views/Shared/_Culture.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@inject Microsoft.Extensions.Options.IOptions<Microsoft.AspNetCore.Builder.RequestLocalizationOptions> locOptions

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{ 
    var culture = Context.Features.Get<Microsoft.AspNetCore.Localization.IRequestCultureFeature>();
    var cultureList = locOptions.Value.SupportedUICultures.Select(x => new SelectListItem { Value = x.Name, Text = localizer.GetString(x.Name) }).ToList();
    var returnUrl = string.IsNullOrWhiteSpace(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}{Context.Request.QueryString}";
}

<head>
    <script src="~/js/jquery/jquery.min.js"></script>
</head>
<script>
</script>
<div>
    <form asp-action="CultureManagement" asp-controller="Home" method="post" asp-route-returnUrl="@returnUrl">
        <select id="languageSelector" name="culture" asp-for="@culture.RequestCulture.UICulture.Name" asp-items="cultureList"
                onchange="this.form.submit()"></select>
    </form>
</div>

TaxiServiceWebUI/Views/Shared/_Layout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Innsbruck Taxi | Airport</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="~/images/logo.png" type="image/x-icon" />

    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="~/css/main/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="~/css/main/css/animate.css">

    <link rel="stylesheet" href="~/css/main/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/main/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/css/main/css/magnific-popup.css">

    <link rel="stylesheet" href="~/css/main/css/aos.css">

    <link rel="stylesheet" href="~/css/main/css/ionicons.min.css">

    <link rel="stylesheet" href="~/css/main/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/css/main/css/jquery.timepicker.css">


    <link rel="stylesheet" href="~/css/main/css/flaticon.css">
    <link href="~/css/icofont/icofont.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/main/css/icomoon.css">
    <link rel="stylesheet" href="~/css/main/css/style.css">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
        <div class="container">
            <a class="navbar-brand" href="@Url.Action("Index","Home")">@localizer["InnsbruckLabel"]<span>@localizer["Taxi"]</span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="oi oi-menu"></span> @localizer["Menu"]
            </button>

            <div class="collapse navbar-collapse" id="ftco-nav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active"><a href="@Url.Action("Index","Home")" class="nav-link">@localizer["Home"]</a></li>
                    <li class="nav-item"><a href="@Url.Action("List","About")" class="nav-link">@localizer["About"]</a></li>
                    <li class="nav-item"><a href="@Url.Action("List","Resort")" class="nav-link">@localizer["SkiResorts"]</a></li>
                    <li class="nav-item"><a href="@Url.Action("BookingService","Reservation")" class="nav-link">@localizer["Booking"]</a></li>
                    <li class="nav-item"><a href="@Url.Action("Info","Contact")" class="nav-link">@localizer["Contact"]</a></li>
                </ul>
                <partial name="_Culture" />
            </div>
        </div>
    </nav>
    <!-- END nav -->

    @RenderBody()

    <footer class="ftco-footer ftco-bg-dark ftco-section">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">@localizer["AboutTaxi"]</h2>
                        <p>@localizer["AboutLabel"]</p>
                        <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                            <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                            <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                            <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4 ml-md-5">
                        <h2 class="ftco-heading-2">@localizer["Info"]</h2>
                        <ul class="list-unstyled">
                            <li><a href="@Url.Action("List","About")" class="py-2 d-block">@localizer["About"]</a></li>
                            <li><a href="@Url.Action("Info","Contact")" class="py-2 d-block">@localizer["Contact"]</a></li>
                            <li><a href="@Url.Action("List","Resort")" class="py-2 d-block">@localizer["SkiResorts"]</a></li>
                            <li><a href="@Url.Action("Index","Home")" class="py-2 d-block">@localizer["Home"]</a></li>
                            <li><a href="@Url.Action("BookingService","Reservation")" class="py-2 d-block">@localizer["Booking"]</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">@localizer["HaveQuestion"]</h2>
                        <div class="block-23 mb-3">
                            <ul>
                                <li>
                                    <span class="icon icon-map-marker"></span><span class="text">
                                        Innsbruck - Wetterhenweg
                                    </span>
                                </li>
                                <li><a><span class="icon icon-phone"></span><span class="text">004366499398308</span></a></li>
                                <li><a href="@Url.Action("Info","Contact")"><span class="icon icon-envelope"></span><span class="text">infoinnsbrucktaxi@gmail.com</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">
                    <p>
                        @localizer["Copyright"] &copy;
                        <script>document.write(new Date().getFullYear());</script> @localizer["AllRights"]
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">
                    <p style="font-size: 0.7em;">KALYONCU SOFTWARE <span>aydincankalyncu@gmail.com</span></p>
                </div>
            </div>
        </div>
    </footer>



    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>

    <script src="~/js/Kontroller.js" type="text/javascript"></script>
    <script src="~/js/BookingEvents.js"></script>
    <script src="~/js/main/js/jquery.min.js"></script>
    <script src="~/js/main/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/js/main/js/popper.min.js"></script>
    <script src="~/js/main/js/bootstrap.min.js"></script>
    <script src="~/js/main/js/jquery.easing.1.3.js"></script>
    <script src="~/js/main/js/jquery.waypoints.min.js"></script>
    <script src="~/js/main/js/jquery.stellar.min.js"></script>
    <script src="~/js/main/js/owl.carousel.min.js"></script>
    <script src="~/js/main/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/main/js/aos.js"></script>
    <script src="~/js/main/js/jquery.animateNumber.min.js"></script>
    <script src="~/js/main/js/bootstrap-datepicker.js"></script>
    <script src="~/js/main/js/jquery.timepicker.min.js"></script>
    <script src="~/js/main/js/scrollax.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="~/js/main/js/google-map.js"></script>
    <script src="~/js/main/js/main.js"></script>
    <script src="~/js/main/js/bootstrap-datepicker.de.js"></script>
    <script src="~/js/main/js/bootstrap-datepicker.en-GB.js"></script>
</body>
</html>