TaxiServiceWebUI/Areas/Admin/Controllers/AddressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Abstract;
using Entities.Concrete;
using Microsoft.AspNetCore.Mvc;
using TaxiServiceWebUI.Areas.Admin.Models;

namespace TaxiServiceWebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AddressController : Controller
    {
        private IAddressService _addressService;
        public AddressController(IAddressService addressService)
        {
            _addressService = addressService;
        }
        
        public IActionResult List()
        {
            var addressList = _addressService.GetAddressList();
            AddressListViewModel model = new AddressListViewModel
            {
                Addresses = addressList
            };
            return View(model);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Address address)
        {
            if (ModelState.IsValid)
            {
                _addressService.Add(address);
                return RedirectToAction("List");
            }
            return View();
            
        }

        public IActionResult Update(int addressId)
        {
            var address = _addressService.GetAddressById(addressId);
            AddressUpdateViewModel model = new AddressUpdateViewModel { Address = address.Data };

            return View(model);
        }

        [HttpPost]
        public IActionResult Update(Address address)
        {
            if (ModelState.IsValid)
            {
                _addressService.Update(address);
                return RedirectToAction("List");
            }
            return View();
        }

        public IActionResult Delete(int addressId)
        {
            var address = _addressService.GetAddressById(addressId);
            if (address.Success)
            {
                _addressService.Delete(addressId);
            }
            return RedirectToAction("List");
        }
    }
}

TaxiServiceWebUI/Areas/Admin/Views/Address/Add.cshtml
@model TaxiServiceWebUI.Areas.Admin.Models.AddressAddViewModel;
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers



<div class="card card-info">
    <div class="card-header">
        <h3 class="card-title">Adres Ekleme Formu</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form class="form-horizontal" asp-controller="Address" asp-action="Add" method="post">
        <div class="card-body">
            <div class="form-group row">
                <label asp-for="Address.Name" class="col-sm-2 col-form-label">Adres</label>
                <div class="col-sm-10">
                    <input type="text" asp-for="Address.Name" class="form-control" placeholder="Adres giriniz.">
                </div>
                <span style="margin-left:5px; color:red; font-weight:bold;" asp-validation-for="Address.Name"></span>
            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <button type="submit" class="btn btn-info">Kaydet</button>
            <a href="@Url.Action("List","Address", new { area = "Admin" })" class="btn btn-default float-right">Geri Dön</a>
        </div>
        <!-- /.card-footer -->
    </form>
</div>

TaxiServiceWebUI/Areas/Admin/Views/Address/List.cshtml
@model TaxiServiceWebUI.Areas.Admin.Models.AddressListViewModel;
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers


<head>
    <link href="~/css/adminlte/dataTables.bootstrap4.css" rel="stylesheet" />
    <script src="~/js/adminlte/jquery.dataTables.js" type="text/javascript"></script>
    <script src="~/js/adminlte/dataTables.bootstrap4.js" type="text/javascript"></script>
</head>

<h2 class="header">Adres Yönetim Paneli</h2>
<hr />
<a class="btn  btn-success" href="@Url.Action("Add","Address", new { area = "Admin"})">Yeni Adres Ekle</a>

<br />
<br />
<br />
<hr />


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title" style="font-weight:bold;">Adres Bilgileri</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0">
                <table id="dataTable" class="table table-hover text-nowrap">
                    <thead style="font-weight:bold;">
                        <tr>
                            <td>Adres Id</td>
                            <td>Adres Adı</td>
                            <td></td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var address in Model.Addresses)
                        {
                            <tr>
                                <td>@address.Id</td>
                                <td>@address.Name</td>
                                <td><a class="btn  btn-info" asp-controller="Address" asp-action="Update" asp-route-addressId="@address.Id">Güncelle</a></td>
                                <td><a class="btn btn-danger" asp-controller="Address" asp-action="Delete" asp-route-addressId="@address.Id">Sil</a></td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>

<script>
    $(function () {
        $('#dataTable').DataTable({
            "paging": true,
            "lengthChange": true,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "language": {
                "lengthMenu": "Sayfada _MENU_ Adet Kayıt Göster",
                "zeroRecords": "kayıt bulunamadı",
                "info": "Gösterilen sayfa _PAGE_ / _PAGES_",
                "infoEmpty": "Kayıt bulunamadı",
                "infoFiltered": "(_MAX_ adet kayıttan süzülen)",
                "search": "Listede Ara:",
                paginate: {
                    first: "İlk",
                    previous: "Önceki",
                    next: "Sonraki",
                    last: "Son"
                }
            }
        });
    });
</script>

TaxiServiceWebUI/Areas/Admin/Views/Address/Update.cshtml
@model TaxiServiceWebUI.Areas.Admin.Models.AddressUpdateViewModel;
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers



<div class="card card-info">
    <div class="card-header">
        <h3 class="card-title">Adres Güncelleme Formu</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form class="form-horizontal" asp-controller="Address" asp-action="Update" method="post">
        <div class="card-body">
            <div class="form-group row">
                <label style="display:none;" asp-for="Address.Id" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-10">
                    <input type="hidden" asp-for="Address.Id" class="form-control" placeholder="Adres Id.">
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="Address.Name" class="col-sm-2 col-form-label">Adres</label>
                <div class="col-sm-10">
                    <input type="text" asp-for="Address.Name" class="form-control" placeholder="Adresi giriniz.">
                </div>
                <span style="margin-left:5px; color:red; font-weight:bold;" asp-validation-for="Address.Name"></span>
            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <button type="submit" class="btn btn-info">Kaydet</button>
            <a href="@Url.Action("List","Address", new { area = "Admin" })" class="btn btn-default float-right">Geri Dön</a>
        </div>
        <!-- /.card-footer -->
    </form>
</div>